### ISSUE TITLE
Mejoras en HIDAP- taller UNALM-FIA (22-27 May 2017)

### ISSUE THREAD

**Issue by omarbenites** [Flavjack/fieldbook#4]
#ToDo Lista de mejoras recogidas del taller de FieldBook y R para la agricultura.

- [ ] El ANOVA (anva) debe ser mostrado en una tabla para descargar. 
- [ ] De la Comparación de Medias, mostrar en una tabla (Mean, CV,  MSerror , HSD, cuadrados medios esperados) (out$statistics).
- [ ] Agregar un módulo de transformaciones (raíz cuadrada, logaritmo, arcosin).
- [ ] En el análisis factorial, sacar un resumen por Factor A y por Factor B. (efectos principales)
- [ ] Poner gráfico del PCA del  factoextra::pca
- [ ] Gráfico de pairs con ggplot2 (Multiples plots para ver correlación y el coeficiente r en cada sub-gráfico).
- [ ] En Statistics, colocar por defecto **Tukey** en **Type**
- [ ] Mostrar debajo del boxplot, una tabla con los outliers.
- [ ] Cuadro resumen de los estadísticos básico (media, moda, mediana, min, max, etc)
